name: Ubuntu
on: push

jobs:
  make:
    runs-on: windows-latest

    steps:
    - run: echo "source 'https://rubygems.org'" >> Gemfile
    - run: echo "gem 'nokogiri'" >> Gemfile
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
    - run: bundle.bat config --local path D:\a\test\test\vendor\bundle
    - run: bundle install
