name: Ubuntu
on: push

jobs:
  make:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04, ubuntu-24.04-arm ]
        test_task: [check]
        configure: ['']
        arch: ['']
        timeout: [40]
        include:
          - test_task: check
            configure: 'cppflags=-DVM_CHECK_MODE'
          - test_task: check
            arch: i686
          - test_task: check
            configure: '--disable-yjit'
          - test_task: check
            configure: '--enable-shared --enable-load-relative'
          - test_task: test-bundler-parallel
            timeout: 50
          - test_task: test-bundled-gems
      fail-fast: false

    runs-on: ${{ matrix.os || ubuntu-22.04 }}

    steps:
      - name: Test
        run: uname -a
